### PR TITLE
Initial Project Structure

### PR DESCRIPTION
**Pull request by hughesd22**
Setting up the basic project structure in preparation for production core

### CODE REVIEW

**Comment by reactivepixel** [comment]
Your initial structure looks good. Keep in mind that if you intend on having multiple components in this repo (not sure if you are) you should isolate them with a wrapping folder around all elements contained within. Here's a short video that gets into that further - https://www.youtube.com/watch?v=CmTOW-29hpQ&index=3&list=PLEBnLDjR5B912lpuj_8kkqx8zxiiXQB61&t=0s

Is this an entire week's worth of work? I only see one day of commits in here and you are pulling directly to master.

This may just be a messaging issue in that we need to better get you on board with the branch model we intend you to use, where you are pull requesting to a dev branch first (frequently) and merging those in at your will, then for the weekly release you make a pull request from Dev > Release and this is where you can catch your last issues before Pushing to the Master (live) branch. It's this final push that we are really critical of and want to take our time evaluating things.

Here's an article that goes deeper into this process - https://nvie.com/posts/a-successful-git-branching-model/

As is, I approve this and you should focus on branching off of and into a Dev branch so that you can work efficiently with only worrying about the big releases being related to the major weekly submissions.
👍

**Comment by hughesd22** [comment]
@reactivepixel When you mention multiple components, what do you mean? You are recommending to wrap these components with a folder to isolate them, but I thought components were stored in the node_modules folder, which is ignored by the repo? I am likely misinterpreting the suggestion. (I'm thinking of npm packages like [body-parser](https://www.npmjs.com/package/body-parser), which may not be what you're referring to)

**Comment by hughesd22** [comment]
@reactivepixel I wasn't sure what development we were supposed to be doing during week 2 since we had to wait for the project specifications doc to be approved, so I just setup the basic project structure in preparation for development.

**Comment by hughesd22** [comment]
@reactivepixel Ah, thanks for informing me of the correct workflow. We didn't really go that in depth in previous classes (just used different branches for each assignment, but never merged branches or used pull requests).

So I am supposed to have two core branches (master, develop) and two types of supporting branches (release, feature). The master branch is the production (live) branch that contains public facing code. The develop branch is where production work will take place. I will create feature branches which branch off the develop branch. These feature branches are transitory and will be merged back into the develop branch (with --no-ff flag) and deleted once the feature the branch is named for is completed. Then at the end of the week, I will create a release branch (with a version number) and submit a pull request from develop->release (so that the release branch mirrors the state of the develop branch at that time) where I will catch any last issues I may have missed. Then I will submit a pull request from that release branch to master and request a code review from an instructor for my milestone pull request assignment. This final pull request from release->master should be free from most errors and the code should be completely functional and ready to be deployed, which is why the instructors will be critical of it.

Am I understanding this process correctly?

**Comment by reactivepixel** [comment]
That is precisely correct! 😄

**Pull request merged**
